// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: edgeList.proto

#ifndef PROTOBUF_edgeList_2eproto__INCLUDED
#define PROTOBUF_edgeList_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_edgeList_2eproto();
void protobuf_AssignDesc_edgeList_2eproto();
void protobuf_ShutdownFile_edgeList_2eproto();

class EdgeList;

// ===================================================================

class EdgeList : public ::google::protobuf::Message {
 public:
  EdgeList();
  virtual ~EdgeList();

  EdgeList(const EdgeList& from);

  inline EdgeList& operator=(const EdgeList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EdgeList& default_instance();

  void Swap(EdgeList* other);

  // implements Message ----------------------------------------------

  EdgeList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EdgeList& from);
  void MergeFrom(const EdgeList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint64 nbrs = 1;
  inline int nbrs_size() const;
  inline void clear_nbrs();
  static const int kNbrsFieldNumber = 1;
  inline ::google::protobuf::uint64 nbrs(int index) const;
  inline void set_nbrs(int index, ::google::protobuf::uint64 value);
  inline void add_nbrs(::google::protobuf::uint64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      nbrs() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_nbrs();

  // @@protoc_insertion_point(class_scope:EdgeList)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > nbrs_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_edgeList_2eproto();
  friend void protobuf_AssignDesc_edgeList_2eproto();
  friend void protobuf_ShutdownFile_edgeList_2eproto();

  void InitAsDefaultInstance();
  static EdgeList* default_instance_;
};
// ===================================================================


// ===================================================================

// EdgeList

// repeated uint64 nbrs = 1;
inline int EdgeList::nbrs_size() const {
  return nbrs_.size();
}
inline void EdgeList::clear_nbrs() {
  nbrs_.Clear();
}
inline ::google::protobuf::uint64 EdgeList::nbrs(int index) const {
  return nbrs_.Get(index);
}
inline void EdgeList::set_nbrs(int index, ::google::protobuf::uint64 value) {
  nbrs_.Set(index, value);
}
inline void EdgeList::add_nbrs(::google::protobuf::uint64 value) {
  nbrs_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
EdgeList::nbrs() const {
  return nbrs_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
EdgeList::mutable_nbrs() {
  return &nbrs_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_edgeList_2eproto__INCLUDED
