// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: edgeList.proto

#ifndef PROTOBUF_edgeList_2eproto__INCLUDED
#define PROTOBUF_edgeList_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_edgeList_2eproto();
void protobuf_AssignDesc_edgeList_2eproto();
void protobuf_ShutdownFile_edgeList_2eproto();

class RecordType;

// ===================================================================

class RecordType : public ::google::protobuf::Message {
 public:
  RecordType();
  virtual ~RecordType();

  RecordType(const RecordType& from);

  inline RecordType& operator=(const RecordType& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RecordType& default_instance();

  void Swap(RecordType* other);

  // implements Message ----------------------------------------------

  RecordType* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RecordType& from);
  void MergeFrom(const RecordType& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint64 nbrs = 1;
  inline int nbrs_size() const;
  inline void clear_nbrs();
  static const int kNbrsFieldNumber = 1;
  inline ::google::protobuf::uint64 nbrs(int index) const;
  inline void set_nbrs(int index, ::google::protobuf::uint64 value);
  inline void add_nbrs(::google::protobuf::uint64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      nbrs() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_nbrs();

  // required uint64 rank = 3;
  inline bool has_rank() const;
  inline void clear_rank();
  static const int kRankFieldNumber = 3;
  inline ::google::protobuf::uint64 rank() const;
  inline void set_rank(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:RecordType)
 private:
  inline void set_has_rank();
  inline void clear_has_rank();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > nbrs_;
  ::google::protobuf::uint64 rank_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_edgeList_2eproto();
  friend void protobuf_AssignDesc_edgeList_2eproto();
  friend void protobuf_ShutdownFile_edgeList_2eproto();

  void InitAsDefaultInstance();
  static RecordType* default_instance_;
};
// ===================================================================


// ===================================================================

// RecordType

// repeated uint64 nbrs = 1;
inline int RecordType::nbrs_size() const {
  return nbrs_.size();
}
inline void RecordType::clear_nbrs() {
  nbrs_.Clear();
}
inline ::google::protobuf::uint64 RecordType::nbrs(int index) const {
  return nbrs_.Get(index);
}
inline void RecordType::set_nbrs(int index, ::google::protobuf::uint64 value) {
  nbrs_.Set(index, value);
}
inline void RecordType::add_nbrs(::google::protobuf::uint64 value) {
  nbrs_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
RecordType::nbrs() const {
  return nbrs_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
RecordType::mutable_nbrs() {
  return &nbrs_;
}

// required uint64 rank = 3;
inline bool RecordType::has_rank() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RecordType::set_has_rank() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RecordType::clear_has_rank() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RecordType::clear_rank() {
  rank_ = GOOGLE_ULONGLONG(0);
  clear_has_rank();
}
inline ::google::protobuf::uint64 RecordType::rank() const {
  return rank_;
}
inline void RecordType::set_rank(::google::protobuf::uint64 value) {
  set_has_rank();
  rank_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_edgeList_2eproto__INCLUDED
